// Generated by gencpp from file geek_gasteiz/SrvGeekRequest.msg
// DO NOT EDIT!


#ifndef GEEK_GASTEIZ_MESSAGE_SRVGEEKREQUEST_H
#define GEEK_GASTEIZ_MESSAGE_SRVGEEKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geek_gasteiz
{
template <class ContainerAllocator>
struct SrvGeekRequest_
{
  typedef SrvGeekRequest_<ContainerAllocator> Type;

  SrvGeekRequest_()
    : x(0)
    , y(0)  {
    }
  SrvGeekRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvGeekRequest_

typedef ::geek_gasteiz::SrvGeekRequest_<std::allocator<void> > SrvGeekRequest;

typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekRequest > SrvGeekRequestPtr;
typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekRequest const> SrvGeekRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geek_gasteiz

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geek_gasteiz': ['/home/igor/catkin_ws/src/geek_gasteiz/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geek_gasteiz/SrvGeekRequest";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvGeekRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geek_gasteiz::SrvGeekRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEEK_GASTEIZ_MESSAGE_SRVGEEKREQUEST_H
