// Generated by gencpp from file geek_gasteiz/SrvGeek.msg
// DO NOT EDIT!


#ifndef GEEK_GASTEIZ_MESSAGE_SRVGEEK_H
#define GEEK_GASTEIZ_MESSAGE_SRVGEEK_H

#include <ros/service_traits.h>


#include <geek_gasteiz/SrvGeekRequest.h>
#include <geek_gasteiz/SrvGeekResponse.h>


namespace geek_gasteiz
{

struct SrvGeek
{

typedef SrvGeekRequest Request;
typedef SrvGeekResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvGeek
} // namespace geek_gasteiz


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geek_gasteiz::SrvGeek > {
  static const char* value()
  {
    return "2071066d24f0fa7611852ac3152d1d50";
  }

  static const char* value(const ::geek_gasteiz::SrvGeek&) { return value(); }
};

template<>
struct DataType< ::geek_gasteiz::SrvGeek > {
  static const char* value()
  {
    return "geek_gasteiz/SrvGeek";
  }

  static const char* value(const ::geek_gasteiz::SrvGeek&) { return value(); }
};


// service_traits::MD5Sum< ::geek_gasteiz::SrvGeekRequest> should match 
// service_traits::MD5Sum< ::geek_gasteiz::SrvGeek > 
template<>
struct MD5Sum< ::geek_gasteiz::SrvGeekRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geek_gasteiz::SrvGeek >::value();
  }
  static const char* value(const ::geek_gasteiz::SrvGeekRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geek_gasteiz::SrvGeekRequest> should match 
// service_traits::DataType< ::geek_gasteiz::SrvGeek > 
template<>
struct DataType< ::geek_gasteiz::SrvGeekRequest>
{
  static const char* value()
  {
    return DataType< ::geek_gasteiz::SrvGeek >::value();
  }
  static const char* value(const ::geek_gasteiz::SrvGeekRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geek_gasteiz::SrvGeekResponse> should match 
// service_traits::MD5Sum< ::geek_gasteiz::SrvGeek > 
template<>
struct MD5Sum< ::geek_gasteiz::SrvGeekResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geek_gasteiz::SrvGeek >::value();
  }
  static const char* value(const ::geek_gasteiz::SrvGeekResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geek_gasteiz::SrvGeekResponse> should match 
// service_traits::DataType< ::geek_gasteiz::SrvGeek > 
template<>
struct DataType< ::geek_gasteiz::SrvGeekResponse>
{
  static const char* value()
  {
    return DataType< ::geek_gasteiz::SrvGeek >::value();
  }
  static const char* value(const ::geek_gasteiz::SrvGeekResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEEK_GASTEIZ_MESSAGE_SRVGEEK_H
