// Generated by gencpp from file geek_gasteiz/SrvGeekResponse.msg
// DO NOT EDIT!


#ifndef GEEK_GASTEIZ_MESSAGE_SRVGEEKRESPONSE_H
#define GEEK_GASTEIZ_MESSAGE_SRVGEEKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geek_gasteiz
{
template <class ContainerAllocator>
struct SrvGeekResponse_
{
  typedef SrvGeekResponse_<ContainerAllocator> Type;

  SrvGeekResponse_()
    : mul(0)  {
    }
  SrvGeekResponse_(const ContainerAllocator& _alloc)
    : mul(0)  {
  (void)_alloc;
    }



   typedef int64_t _mul_type;
  _mul_type mul;




  typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvGeekResponse_

typedef ::geek_gasteiz::SrvGeekResponse_<std::allocator<void> > SrvGeekResponse;

typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekResponse > SrvGeekResponsePtr;
typedef boost::shared_ptr< ::geek_gasteiz::SrvGeekResponse const> SrvGeekResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geek_gasteiz

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geek_gasteiz': ['/home/igor/catkin_ws/src/geek_gasteiz/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f17363cd17c14ac0fae7fd5c952ba3d";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f17363cd17c14acULL;
  static const uint64_t static_value2 = 0x0fae7fd5c952ba3dULL;
};

template<class ContainerAllocator>
struct DataType< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geek_gasteiz/SrvGeekResponse";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mul\n\
\n\
";
  }

  static const char* value(const ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mul);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvGeekResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geek_gasteiz::SrvGeekResponse_<ContainerAllocator>& v)
  {
    s << indent << "mul: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mul);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEEK_GASTEIZ_MESSAGE_SRVGEEKRESPONSE_H
